
version: "3.9"
services:
  lester:
    build: .
    container_name: lester
    environment:
      # Rabbit corre en la MISMA VM en el contenedor "rabbitmq" y puerto interno 5672
      AMQP_URL: "amqp://heist:heist123@rabbitmq:5672/"
      LESTER_PORT: "50051"
    ports:
      - "50051:50051"
    networks:
      - heistnet

networks:
  heistnet:
    external: true

