services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports: ["5672:5672", "15672:15672"]
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 20

  lester:
    build:
      context: ./lester     
    container_name: lester
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
    ports: ["50051:50051"]
