// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: trevor.proto

package trevorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrewService_StartDistraction_FullMethodName = "/trevor.CrewService/StartDistraction"
	CrewService_StartHeist_FullMethodName       = "/trevor.CrewService/StartHeist"
	CrewService_QueryStatus_FullMethodName      = "/trevor.CrewService/QueryStatus"
	CrewService_GetLoot_FullMethodName          = "/trevor.CrewService/GetLoot"
	CrewService_ConfirmPayment_FullMethodName   = "/trevor.CrewService/ConfirmPayment"
)

// CrewServiceClient is the client API for CrewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===== Servicio =====
type CrewServiceClient interface {
	StartDistraction(ctx context.Context, in *StartDistractionReq, opts ...grpc.CallOption) (*Ack, error)
	StartHeist(ctx context.Context, in *StartHeistReq, opts ...grpc.CallOption) (*Ack, error)
	QueryStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusReply, error)
	GetLoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LootReply, error)
	ConfirmPayment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentReply, error)
}

type crewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrewServiceClient(cc grpc.ClientConnInterface) CrewServiceClient {
	return &crewServiceClient{cc}
}

func (c *crewServiceClient) StartDistraction(ctx context.Context, in *StartDistractionReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrewService_StartDistraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) StartHeist(ctx context.Context, in *StartHeistReq, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CrewService_StartHeist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) QueryStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, CrewService_QueryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) GetLoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LootReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LootReply)
	err := c.cc.Invoke(ctx, CrewService_GetLoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) ConfirmPayment(ctx context.Context, in *PaymentReq, opts ...grpc.CallOption) (*PaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentReply)
	err := c.cc.Invoke(ctx, CrewService_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrewServiceServer is the server API for CrewService service.
// All implementations must embed UnimplementedCrewServiceServer
// for forward compatibility.
//
// ===== Servicio =====
type CrewServiceServer interface {
	StartDistraction(context.Context, *StartDistractionReq) (*Ack, error)
	StartHeist(context.Context, *StartHeistReq) (*Ack, error)
	QueryStatus(context.Context, *StatusReq) (*StatusReply, error)
	GetLoot(context.Context, *Empty) (*LootReply, error)
	ConfirmPayment(context.Context, *PaymentReq) (*PaymentReply, error)
	mustEmbedUnimplementedCrewServiceServer()
}

// UnimplementedCrewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrewServiceServer struct{}

func (UnimplementedCrewServiceServer) StartDistraction(context.Context, *StartDistractionReq) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDistraction not implemented")
}
func (UnimplementedCrewServiceServer) StartHeist(context.Context, *StartHeistReq) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartHeist not implemented")
}
func (UnimplementedCrewServiceServer) QueryStatus(context.Context, *StatusReq) (*StatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryStatus not implemented")
}
func (UnimplementedCrewServiceServer) GetLoot(context.Context, *Empty) (*LootReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoot not implemented")
}
func (UnimplementedCrewServiceServer) ConfirmPayment(context.Context, *PaymentReq) (*PaymentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedCrewServiceServer) mustEmbedUnimplementedCrewServiceServer() {}
func (UnimplementedCrewServiceServer) testEmbeddedByValue()                     {}

// UnsafeCrewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrewServiceServer will
// result in compilation errors.
type UnsafeCrewServiceServer interface {
	mustEmbedUnimplementedCrewServiceServer()
}

func RegisterCrewServiceServer(s grpc.ServiceRegistrar, srv CrewServiceServer) {
	// If the following call pancis, it indicates UnimplementedCrewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrewService_ServiceDesc, srv)
}

func _CrewService_StartDistraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDistractionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).StartDistraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_StartDistraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).StartDistraction(ctx, req.(*StartDistractionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_StartHeist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartHeistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).StartHeist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_StartHeist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).StartHeist(ctx, req.(*StartHeistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_QueryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).QueryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_QueryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).QueryStatus(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_GetLoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).GetLoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_GetLoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).GetLoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).ConfirmPayment(ctx, req.(*PaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CrewService_ServiceDesc is the grpc.ServiceDesc for CrewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trevor.CrewService",
	HandlerType: (*CrewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartDistraction",
			Handler:    _CrewService_StartDistraction_Handler,
		},
		{
			MethodName: "StartHeist",
			Handler:    _CrewService_StartHeist_Handler,
		},
		{
			MethodName: "QueryStatus",
			Handler:    _CrewService_QueryStatus_Handler,
		},
		{
			MethodName: "GetLoot",
			Handler:    _CrewService_GetLoot_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _CrewService_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trevor.proto",
}
