// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: franklin.proto

package franklinpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhaseState int32

const (
	PhaseState_WAITING PhaseState = 0
	PhaseState_RUNNING PhaseState = 1
	PhaseState_SUCCESS PhaseState = 2
	PhaseState_FAIL    PhaseState = 3
)

// Enum value maps for PhaseState.
var (
	PhaseState_name = map[int32]string{
		0: "WAITING",
		1: "RUNNING",
		2: "SUCCESS",
		3: "FAIL",
	}
	PhaseState_value = map[string]int32{
		"WAITING": 0,
		"RUNNING": 1,
		"SUCCESS": 2,
		"FAIL":    3,
	}
)

func (x PhaseState) Enum() *PhaseState {
	p := new(PhaseState)
	*p = x
	return p
}

func (x PhaseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseState) Descriptor() protoreflect.EnumDescriptor {
	return file_franklin_proto_enumTypes[0].Descriptor()
}

func (PhaseState) Type() protoreflect.EnumType {
	return &file_franklin_proto_enumTypes[0]
}

func (x PhaseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseState.Descriptor instead.
func (PhaseState) EnumDescriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{0}
}

type StartDistractionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prob          int32                  `protobuf:"varint,1,opt,name=prob,proto3" json:"prob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDistractionReq) Reset() {
	*x = StartDistractionReq{}
	mi := &file_franklin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDistractionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDistractionReq) ProtoMessage() {}

func (x *StartDistractionReq) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDistractionReq.ProtoReflect.Descriptor instead.
func (*StartDistractionReq) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{0}
}

func (x *StartDistractionReq) GetProb() int32 {
	if x != nil {
		return x.Prob
	}
	return 0
}

type StartHeistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prob          int32                  `protobuf:"varint,1,opt,name=prob,proto3" json:"prob,omitempty"`
	PoliceRisk    int32                  `protobuf:"varint,2,opt,name=police_risk,json=policeRisk,proto3" json:"police_risk,omitempty"`
	BaseLoot      int32                  `protobuf:"varint,3,opt,name=base_loot,json=baseLoot,proto3" json:"base_loot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartHeistReq) Reset() {
	*x = StartHeistReq{}
	mi := &file_franklin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeistReq) ProtoMessage() {}

func (x *StartHeistReq) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeistReq.ProtoReflect.Descriptor instead.
func (*StartHeistReq) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{1}
}

func (x *StartHeistReq) GetProb() int32 {
	if x != nil {
		return x.Prob
	}
	return 0
}

func (x *StartHeistReq) GetPoliceRisk() int32 {
	if x != nil {
		return x.PoliceRisk
	}
	return 0
}

func (x *StartHeistReq) GetBaseLoot() int32 {
	if x != nil {
		return x.BaseLoot
	}
	return 0
}

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_franklin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{2}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PhaseState             `protobuf:"varint,1,opt,name=state,proto3,enum=franklin.PhaseState" json:"state,omitempty"`
	FailReason    string                 `protobuf:"bytes,2,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`
	TurnsDone     int32                  `protobuf:"varint,3,opt,name=turns_done,json=turnsDone,proto3" json:"turns_done,omitempty"`
	Stars         int32                  `protobuf:"varint,4,opt,name=stars,proto3" json:"stars,omitempty"`
	ExtraLoot     int32                  `protobuf:"varint,5,opt,name=extra_loot,json=extraLoot,proto3" json:"extra_loot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_franklin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReply) GetState() PhaseState {
	if x != nil {
		return x.State
	}
	return PhaseState_WAITING
}

func (x *StatusReply) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *StatusReply) GetTurnsDone() int32 {
	if x != nil {
		return x.TurnsDone
	}
	return 0
}

func (x *StatusReply) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *StatusReply) GetExtraLoot() int32 {
	if x != nil {
		return x.ExtraLoot
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_franklin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{4}
}

type LootReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalLoot     int32                  `protobuf:"varint,1,opt,name=total_loot,json=totalLoot,proto3" json:"total_loot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootReply) Reset() {
	*x = LootReply{}
	mi := &file_franklin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootReply) ProtoMessage() {}

func (x *LootReply) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootReply.ProtoReflect.Descriptor instead.
func (*LootReply) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{5}
}

func (x *LootReply) GetTotalLoot() int32 {
	if x != nil {
		return x.TotalLoot
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ExtraLoot     int32                  `protobuf:"varint,2,opt,name=ExtraLoot,proto3" json:"ExtraLoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_franklin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Ack) GetExtraLoot() int32 {
	if x != nil {
		return x.ExtraLoot
	}
	return 0
}

type PaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReq) Reset() {
	*x = PaymentReq{}
	mi := &file_franklin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReq) ProtoMessage() {}

func (x *PaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReq.ProtoReflect.Descriptor instead.
func (*PaymentReq) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentReply) Reset() {
	*x = PaymentReply{}
	mi := &file_franklin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentReply) ProtoMessage() {}

func (x *PaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentReply.ProtoReflect.Descriptor instead.
func (*PaymentReply) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PaymentReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_franklin_proto protoreflect.FileDescriptor

const file_franklin_proto_rawDesc = "" +
	"\n" +
	"\x0efranklin.proto\x12\bfranklin\")\n" +
	"\x13StartDistractionReq\x12\x12\n" +
	"\x04prob\x18\x01 \x01(\x05R\x04prob\"a\n" +
	"\rStartHeistReq\x12\x12\n" +
	"\x04prob\x18\x01 \x01(\x05R\x04prob\x12\x1f\n" +
	"\vpolice_risk\x18\x02 \x01(\x05R\n" +
	"policeRisk\x12\x1b\n" +
	"\tbase_loot\x18\x03 \x01(\x05R\bbaseLoot\"\v\n" +
	"\tStatusReq\"\xae\x01\n" +
	"\vStatusReply\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.franklin.PhaseStateR\x05state\x12\x1f\n" +
	"\vfail_reason\x18\x02 \x01(\tR\n" +
	"failReason\x12\x1d\n" +
	"\n" +
	"turns_done\x18\x03 \x01(\x05R\tturnsDone\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x05R\x05stars\x12\x1d\n" +
	"\n" +
	"extra_loot\x18\x05 \x01(\x05R\textraLoot\"\a\n" +
	"\x05Empty\"*\n" +
	"\tLootReply\x12\x1d\n" +
	"\n" +
	"total_loot\x18\x01 \x01(\x05R\ttotalLoot\"5\n" +
	"\x03Ack\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1c\n" +
	"\tExtraLoot\x18\x02 \x01(\x05R\tExtraLoot\"$\n" +
	"\n" +
	"PaymentReq\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\":\n" +
	"\fPaymentReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse*=\n" +
	"\n" +
	"PhaseState\x12\v\n" +
	"\aWAITING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\b\n" +
	"\x04FAIL\x10\x032\xb1\x02\n" +
	"\vCrewService\x12@\n" +
	"\x10StartDistraction\x12\x1d.franklin.StartDistractionReq\x1a\r.franklin.Ack\x124\n" +
	"\n" +
	"StartHeist\x12\x17.franklin.StartHeistReq\x1a\r.franklin.Ack\x129\n" +
	"\vQueryStatus\x12\x13.franklin.StatusReq\x1a\x15.franklin.StatusReply\x12/\n" +
	"\aGetLoot\x12\x0f.franklin.Empty\x1a\x13.franklin.LootReply\x12>\n" +
	"\x0eConfirmPayment\x12\x14.franklin.PaymentReq\x1a\x16.franklin.PaymentReplyB\x1bZ\x19franklin/proto;franklinpbb\x06proto3"

var (
	file_franklin_proto_rawDescOnce sync.Once
	file_franklin_proto_rawDescData []byte
)

func file_franklin_proto_rawDescGZIP() []byte {
	file_franklin_proto_rawDescOnce.Do(func() {
		file_franklin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_franklin_proto_rawDesc), len(file_franklin_proto_rawDesc)))
	})
	return file_franklin_proto_rawDescData
}

var file_franklin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_franklin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_franklin_proto_goTypes = []any{
	(PhaseState)(0),             // 0: franklin.PhaseState
	(*StartDistractionReq)(nil), // 1: franklin.StartDistractionReq
	(*StartHeistReq)(nil),       // 2: franklin.StartHeistReq
	(*StatusReq)(nil),           // 3: franklin.StatusReq
	(*StatusReply)(nil),         // 4: franklin.StatusReply
	(*Empty)(nil),               // 5: franklin.Empty
	(*LootReply)(nil),           // 6: franklin.LootReply
	(*Ack)(nil),                 // 7: franklin.Ack
	(*PaymentReq)(nil),          // 8: franklin.PaymentReq
	(*PaymentReply)(nil),        // 9: franklin.PaymentReply
}
var file_franklin_proto_depIdxs = []int32{
	0, // 0: franklin.StatusReply.state:type_name -> franklin.PhaseState
	1, // 1: franklin.CrewService.StartDistraction:input_type -> franklin.StartDistractionReq
	2, // 2: franklin.CrewService.StartHeist:input_type -> franklin.StartHeistReq
	3, // 3: franklin.CrewService.QueryStatus:input_type -> franklin.StatusReq
	5, // 4: franklin.CrewService.GetLoot:input_type -> franklin.Empty
	8, // 5: franklin.CrewService.ConfirmPayment:input_type -> franklin.PaymentReq
	7, // 6: franklin.CrewService.StartDistraction:output_type -> franklin.Ack
	7, // 7: franklin.CrewService.StartHeist:output_type -> franklin.Ack
	4, // 8: franklin.CrewService.QueryStatus:output_type -> franklin.StatusReply
	6, // 9: franklin.CrewService.GetLoot:output_type -> franklin.LootReply
	9, // 10: franklin.CrewService.ConfirmPayment:output_type -> franklin.PaymentReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_franklin_proto_init() }
func file_franklin_proto_init() {
	if File_franklin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_franklin_proto_rawDesc), len(file_franklin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_franklin_proto_goTypes,
		DependencyIndexes: file_franklin_proto_depIdxs,
		EnumInfos:         file_franklin_proto_enumTypes,
		MessageInfos:      file_franklin_proto_msgTypes,
	}.Build()
	File_franklin_proto = out.File
	file_franklin_proto_goTypes = nil
	file_franklin_proto_depIdxs = nil
}
