
version: "3.8"
services:
  franklin:
    container_name: trevor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AMQP_URL: "amqp://heist:heist123@10.35.168.15:5673/"
      FRANKLIN_PORT: "50053"
    ports:
      - "50053:50053"
    restart: unless-stopped
